name: mesh-fastpath
channels:
  - conda-forge
dependencies:
  # general
  - python=3.12
  - jupyterlab=3
  # specific
  - pandas=2.2.3
  - numpy=2.2.1
  - scikit-learn=1.6.0
  - seaborn=0.13.2
  - matplotlib=3.10
  - plotly=5.14.1
